language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: L+doGDl4AbzTSb5f8DUEbmBtOxRPbzhjRj3mjYDfhSrWtDON+LBbR0FR0WmsttfZhruyD5KuMeNQjKsQPGYo+h0Wnhzz20DViFWc1ImzVahujKeQ7fF4RjISmPbUHmlzrN2ESkiEt7mxHRYxbZoJEUf86AwpeVQAXMPnYixJrsCBX47YNXSl4Dv3VF1nyW/q2+yukXqu4vfiroh4fnhyOLV2X1htOG9Z9rE/DYn3oTcQZtlYWQ4nvz5bSY+c5g220Om6DEPygz6JLMKJpI/HwxrQkKI5VdbKL8NQ8wzCgc6y/CVyqPFe2mrn5hXxAaMQoeTavxbEhMFb+lId2VBc7sjM2SA/fpOWeaogebScYUrgrqP1UjrJtDwhyT7JGfNcC0HX4g+MK1DJG3AMyGwkb07f+8DPtsBpgNVMOboevlAnF9mR5/k/08hO76H79cvylGRNe9sB5nOdDYJDAMkhRyWNy+4Xj+Myi0Rp8Cg7UeT2Eoz/Cu80344CUimqO0oLuONYvItpcwhWLKj6An9IQmFsAo9waYUkPKKyeCk+v6G8GzqwTlz4fJ/yHv4BDurVgen0SfntK9BdOjfDzKGv/prIizJYORcFvu3KbmvQXLSzG9npa5uF9JzihOO30mFkqt4/4y5c3Zj40JHcbvGsXY9JiIwhoVmCtUD0V8vprAU=
  app: calm-lowlands-64387
  on:
    repo: sobhit000/dream-journal-app-client
